/**
 * KanjiVG Bundled Kanji Index
 *
 * Generated by scripts/download-kanjivg-bundle.js
 * Date: 2026-03-10T00:54:18.127Z
 *
 * Data Attribution:
 * KanjiVG data © Ulrich Apel, CC BY-SA 3.0
 * https://kanjivg.tagaini.net/
 *
 * Contains 25 pre-bundled kanji for instant offline access.
 * SVG content is embedded as strings for React Native compatibility.
 */

export const BUNDLED_KANJI_IDS = [
  'U+4E00', // 一
  'U+4E8C', // 二
  'U+4E09', // 三
  'U+4EBA', // 人
  'U+65E5', // 日
  'U+56FD', // 国
  'U+672C', // 本
  'U+5927', // 大
  'U+5E74', // 年
  'U+4E2D', // 中
  'U+51FA', // 出
  'U+4E0A', // 上
  'U+751F', // 生
  'U+6642', // 時
  'U+624B', // 手
  'U+884C', // 行
  'U+524D', // 前
  'U+5F8C', // 後
  'U+898B', // 見
  'U+4E0B', // 下
  'U+6708', // 月
  'U+5B50', // 子
  'U+5206', // 分
  'U+9593', // 間
  'U+5B66', // 学
];

/**
 * Static mapping of kanji IDs to SVG content (as strings)
 * Embedded during bundle generation for React Native compatibility
 */
const BUNDLED_SVG_DATA: Record<string, string> = {
  'U+4E00': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_04e00" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:04e00" kvg:element="一" kvg:radical="general">
	<path id="kvg:04e00-s1" kvg:type="㇐" d="M11,54.25c3.19,0.62,6.25,0.75,9.73,0.5c20.64-1.5,50.39-5.12,68.58-5.24c3.6-0.02,5.77,0.24,7.57,0.49"/>
</g>
</g>
<g id="kvg:StrokeNumbers_04e00" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 4.25 54.13)">1</text>
</g>
</svg>
`, // 一
  'U+4E8C': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_04e8c" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:04e8c" kvg:element="二" kvg:radical="general">
	<g id="kvg:04e8c-g1" kvg:position="top">
		<path id="kvg:04e8c-s1" kvg:type="㇐" d="M25.25,32.4c1.77,0.37,4.78,0.56,6.55,0.37c10.82-1.15,28.82-3.4,41.24-3.76c2.95-0.09,4.73,0.18,6.21,0.36"/>
	</g>
	<g id="kvg:04e8c-g2" kvg:position="bottom">
		<path id="kvg:04e8c-s2" kvg:type="㇐" d="M12,80.75c2.37,0.5,6.73,0.67,9.09,0.5c23.79-1.75,45.04-4.12,67.49-4.74c3.95-0.11,6.32,0.24,8.3,0.49"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_04e8c" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 17.50 33.13)">1</text>
	<text transform="matrix(1 0 0 1 3.50 81.50)">2</text>
</g>
</svg>
`, // 二
  'U+4E09': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_04e09" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:04e09" kvg:element="三">
	<g id="kvg:04e09-g1" kvg:element="一" kvg:position="top" kvg:radical="general">
		<path id="kvg:04e09-s1" kvg:type="㇐" d="M27.5,23.65c3.09,0.73,6.29,0.36,9.4,0.06c10.2-1,27-2.94,38.97-3.57c3.06-0.16,6.09-0.2,9.14,0.23"/>
	</g>
	<g id="kvg:04e09-g2" kvg:position="bottom">
		<g id="kvg:04e09-g3" kvg:element="一">
			<path id="kvg:04e09-s2" kvg:type="㇐" d="M28.75,55.14c3.13,0.76,6.46,0.43,9.64,0.2c10.03-0.72,23.97-2.63,34.73-3.12c2.7-0.12,5.45-0.16,8.13,0.3"/>
		</g>
		<g id="kvg:04e09-g4" kvg:element="一">
			<path id="kvg:04e09-s3" kvg:type="㇐" d="M13,87.83c3.94,1.01,7.72,0.96,11.75,0.72c18.41-1.07,41.27-3.39,61.12-4.07c3.63-0.13,7.2-0.1,10.75,0.78"/>
		</g>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_04e09" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 18.00 25.78)">1</text>
	<text transform="matrix(1 0 0 1 18.75 57.13)">2</text>
	<text transform="matrix(1 0 0 1 3.75 91.63)">3</text>
</g>
</svg>
`, // 三
  'U+4EBA': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_04eba" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:04eba" kvg:element="人" kvg:radical="general">
	<path id="kvg:04eba-s1" kvg:type="㇒" d="M54.5,20c0.37,2.12,0.23,4.03-0.22,6.27C51.68,39.48,38.25,72.25,16.5,87.25"/>
	<path id="kvg:04eba-s2" kvg:type="㇏" d="M46,54.25c6.12,6,25.51,22.24,35.52,29.72c3.66,2.73,6.94,4.64,11.48,5.53"/>
</g>
</g>
<g id="kvg:StrokeNumbers_04eba" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 45.50 19.50)">1</text>
	<text transform="matrix(1 0 0 1 52.50 55.63)">2</text>
</g>
</svg>
`, // 人
  'U+65E5': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_065e5" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:065e5" kvg:element="日" kvg:radical="general">
	<path id="kvg:065e5-s1" kvg:type="㇑" d="M31.5,24.5c1.12,1.12,1.74,2.75,1.74,4.75c0,1.6-0.16,38.11-0.09,53.5c0.02,3.82,0.05,6.35,0.09,6.75"/>
	<path id="kvg:065e5-s2" kvg:type="㇕a" d="M33.48,26c0.8-0.05,37.67-3.01,40.77-3.25c3.19-0.25,5,1.75,5,4.25c0,4-0.22,40.84-0.23,56c0,3.48,0,5.72,0,6"/>
	<path id="kvg:065e5-s3" kvg:type="㇐a" d="M34.22,55.25c7.78-0.5,35.9-2.5,44.06-2.75"/>
	<path id="kvg:065e5-s4" kvg:type="㇐a" d="M34.23,86.5c10.52-0.75,34.15-2.12,43.81-2.25"/>
</g>
</g>
<g id="kvg:StrokeNumbers_065e5" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 25.25 32.63)">1</text>
	<text transform="matrix(1 0 0 1 34.50 22.50)">2</text>
	<text transform="matrix(1 0 0 1 37.50 51.50)">3</text>
	<text transform="matrix(1 0 0 1 37.50 83.50)">4</text>
</g>
</svg>
`, // 日
  'U+56FD': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_056fd" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:056fd" kvg:element="国">
	<g id="kvg:056fd-g1" kvg:element="囗" kvg:part="1" kvg:position="kamae" kvg:radical="general">
		<path id="kvg:056fd-s1" kvg:type="㇑" d="M19,16.82c1.09,1.09,1.61,2.51,1.61,4.41c0,14.65-0.22,44.9-0.22,71.53c0,1.95-0.06,3.86-0.09,5.75"/>
		<path id="kvg:056fd-s2" kvg:type="㇕a" d="M21.52,18.67C41.38,16.75,74.03,13.5,85,13.5c3.38,0,5,1.85,5,5.25c0,15.36-0.04,47.89-0.08,70.62c0,1.68,0,3.31,0,4.88"/>
	</g>
	<g id="kvg:056fd-g2" kvg:element="玉" kvg:phon="或V">
		<g id="kvg:056fd-g3" kvg:element="王" kvg:original="玉" kvg:partial="true">
			<path id="kvg:056fd-s3" kvg:type="㇐" d="M35.12,33.88c1.32,0.28,4.2,0.44,5.51,0.28c10.47-1.29,20.62-2.54,28.62-3.13c2.02-0.15,3.88-0.19,5.56,0.04"/>
			<path id="kvg:056fd-s4" kvg:type="㇑a" d="M52.8,34.89c0.96,0.97,1.47,2.48,1.47,3.81c0,3.99-0.13,24.74-0.09,33.55"/>
			<path id="kvg:056fd-s5" kvg:type="㇐" d="M37.58,52.16c1.79,0.22,3.41,0.14,5.36-0.08c7.56-0.83,17.56-1.99,25.38-2.8c1.25-0.13,4.02-0.15,5.89,0.17"/>
			<path id="kvg:056fd-s6" kvg:type="㇐" d="M31.08,75.14c1.54,0.36,3.85,0.28,5.19,0.16c9.98-0.92,25.85-2.67,37.03-3.54c2.15-0.17,5.04-0.18,6.12,0.13"/>
		</g>
		<g id="kvg:056fd-g4" kvg:element="丶">
			<path id="kvg:056fd-s7" kvg:type="㇔" d="M67.75,56.62c3,1.75,6.12,5.12,8,8.38"/>
		</g>
	</g>
	<g id="kvg:056fd-g5" kvg:element="囗" kvg:part="2" kvg:position="kamae" kvg:radical="general">
		<path id="kvg:056fd-s8" kvg:type="㇐a" d="M21.5,93.01c14.25-0.51,48.38-1.89,67-2.51"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_056fd" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 12.50 25.63)">1</text>
	<text transform="matrix(1 0 0 1 22.50 14.50)">2</text>
	<text transform="matrix(1 0 0 1 27.75 35.50)">3</text>
	<text transform="matrix(1 0 0 1 45.75 43.50)">4</text>
	<text transform="matrix(1 0 0 1 30.50 54.13)">5</text>
	<text transform="matrix(1 0 0 1 29.25 70.63)">6</text>
	<text transform="matrix(1 0 0 1 77.25 60.13)">7</text>
	<text transform="matrix(1 0 0 1 25.50 88.63)">8</text>
</g>
</svg>
`, // 国
  'U+672C': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_0672c" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:0672c" kvg:element="本">
	<g id="kvg:0672c-g1" kvg:element="木" kvg:radical="tradit">
		<path id="kvg:0672c-s1" kvg:type="㇐" d="M20.5,33.5c1.93,0.62,4.91,1.07,8.1,0.75C42.43,32.88,66,30.75,79.64,30c3.2-0.18,7.22,0.25,9.23,0.5"/>
		<g id="kvg:0672c-g2" kvg:element="丨" kvg:radical="nelson">
			<path id="kvg:0672c-s2" kvg:type="㇑" d="M52.1,11.12c1.25,1.25,2.05,3.23,2.05,4.99c0,0.84,0,57.16-0.02,76.76c-0.01,3.96-0.01,6.42-0.02,6.62"/>
		</g>
		<path id="kvg:0672c-s3" kvg:type="㇒" d="M51.75,33.5c0,1-0.41,2.22-1.29,3.88C43.62,50.25,30.12,65.5,13.25,75.5"/>
		<path id="kvg:0672c-s4" kvg:type="㇏" d="M54.75,35.5c4.92,5.74,23.48,23.33,32.85,31.27c2.58,2.18,5.16,4.41,8.52,5.23"/>
	</g>
	<path id="kvg:0672c-s5" kvg:type="㇐" d="M33.88,73.92c1.5,0.46,2.74,0.75,5.3,0.59c9.95-0.63,21.2-2.13,27.96-2.95c1.93-0.23,3.62-0.31,6-0.02"/>
</g>
</g>
<g id="kvg:StrokeNumbers_0672c" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 13.50 34.50)">1</text>
	<text transform="matrix(1 0 0 1 42.50 11.50)">2</text>
	<text transform="matrix(1 0 0 1 38.50 44.50)">3</text>
	<text transform="matrix(1 0 0 1 66.50 43.50)">4</text>
	<text transform="matrix(1 0 0 1 26.50 77.50)">5</text>
</g>
</svg>
`, // 本
  'U+5927': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_05927" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:05927" kvg:element="大" kvg:radical="general">
	<path id="kvg:05927-s1" kvg:type="㇐" d="M19.38,48.25c1.49,0.51,5.03,0.89,7.6,0.49C41.12,46.5,63,43,77.19,42.44c2.7-0.11,4.87-0.06,7.31,0.33"/>
	<path id="kvg:05927-s2" kvg:type="㇒" d="M49.5,18c0.88,2.12,1.03,4.16,0.99,6.32C50,57,37.75,81.12,18,91.75"/>
	<path id="kvg:05927-s3" kvg:type="㇏" d="M49.5,46c9,10.5,28.5,36.25,37.49,43.28c3.06,2.39,5.62,3.75,7.01,3.97"/>
</g>
</g>
<g id="kvg:StrokeNumbers_05927" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 12.75 49.63)">1</text>
	<text transform="matrix(1 0 0 1 40.50 18.50)">2</text>
	<text transform="matrix(1 0 0 1 61.50 55.63)">3</text>
</g>
</svg>
`, // 大
  'U+5E74': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_05e74" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:05e74" kvg:element="年">
	<g id="kvg:05e74-g1" kvg:element="丿" kvg:radical="nelson">
		<path id="kvg:05e74-s1" kvg:type="㇒" d="M40.01,11.89c0.24,1.61-0.01,2.86-0.84,4.46c-2.53,4.84-6.91,11.4-15.86,19.62"/>
	</g>
	<g id="kvg:05e74-g2" kvg:element="干" kvg:part="1" kvg:radical="tradit">
		<path id="kvg:05e74-s2" kvg:type="㇐" d="M39.13,23.62c2.25,0.38,4.4,0.18,5.79,0.03c11.7-1.27,21.33-2.9,33.22-4.07c2.3-0.23,4.2,0,5.35,0.26"/>
		<g id="kvg:05e74-g3" kvg:element="十">
			<path id="kvg:05e74-s3" kvg:type="㇐" d="M30.13,43.59c1.36,0.33,3.87,0.46,5.21,0.33c10.91-1.05,28.53-3.42,40.78-4.26c2.26-0.15,3.63,0.16,4.76,0.32"/>
		</g>
	</g>
	<path id="kvg:05e74-s4" kvg:type="㇑a" d="M33.75,44.5c1,1.25,1,1.97,1.01,3.5C34.8,52.33,35,65.29,35,66.25"/>
	<path id="kvg:05e74-s5" kvg:type="㇐" d="M13.88,67.74c1.97,0.47,5.61,0.66,7.57,0.47c20.21-2.03,36.35-4.62,66.65-5.31c3.29-0.08,5.26,0.22,6.91,0.46"/>
	<g id="kvg:05e74-g4" kvg:element="干" kvg:part="2" kvg:radical="tradit">
		<path id="kvg:05e74-s6" kvg:type="㇑" d="M56.56,25.46c1.12,1.12,1.79,3.54,1.79,4.94c0,0.89-0.05,44.26-0.13,61.6c-0.01,3.12-0.03,5.39-0.05,6.38"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_05e74" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 32.25 11.50)">1</text>
	<text transform="matrix(1 0 0 1 46.50 19.50)">2</text>
	<text transform="matrix(1 0 0 1 31.50 41.50)">3</text>
	<text transform="matrix(1 0 0 1 27.50 53.50)">4</text>
	<text transform="matrix(1 0 0 1 6.50 69.50)">5</text>
	<text transform="matrix(1 0 0 1 50.50 33.50)">6</text>
</g>
</svg>
`, // 年
  'U+4E2D': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_04e2d" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:04e2d" kvg:element="中">
	<g id="kvg:04e2d-g1" kvg:element="口">
		<path id="kvg:04e2d-s1" kvg:type="㇑" d="M19.89,36.87c1,1,1.74,2.25,2.01,3.65c1.13,5.71,2.58,13.06,4.17,22.97c0.27,1.68,0.55,4.43,0.83,6.26"/>
		<path id="kvg:04e2d-s2" kvg:type="㇕b" d="M23.33,39.51C37.12,37.62,70.88,34,84,33.24c4.38-0.25,6,1.14,5.12,4.42c-1.53,5.7-5.61,20.18-6.12,22.09"/>
		<path id="kvg:04e2d-s3" kvg:type="㇐b" d="M27.74,64.84C40.12,63.62,61.86,62.2,79,60.77c2.36-0.2,5.75-0.27,7.25-0.27"/>
	</g>
	<g id="kvg:04e2d-g2" kvg:element="丨" kvg:radical="general">
		<path id="kvg:04e2d-s4" kvg:type="㇑" d="M52.5,11.5c1.44,1.44,2.25,3.5,2.25,5.06c0,0.9,0.06,56.6-0.15,76.69c-0.03,3.3-0.07,5.6-0.1,6.5"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_04e2d" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 14.50 45.13)">1</text>
	<text transform="matrix(1 0 0 1 24.50 35.50)">2</text>
	<text transform="matrix(1 0 0 1 30.50 60.75)">3</text>
	<text transform="matrix(1 0 0 1 43.50 12.50)">4</text>
</g>
</svg>
`, // 中
  'U+51FA': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_051fa" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:051fa" kvg:element="出">
	<g id="kvg:051fa-g1" kvg:element="山">
		<g id="kvg:051fa-g2" kvg:element="丨" kvg:radical="nelson">
			<path id="kvg:051fa-s1" kvg:type="㇑a" d="M52.76,13.38c1.42,1.42,1.86,2.91,1.86,5.31c0,3.18,0.19,61.81,0.19,68.31"/>
		</g>
		<path id="kvg:051fa-s2" kvg:type="㇄a" d="M29.02,36.13c0.98,1.12,1.23,2.87,1.06,4.04c-0.4,2.82-1.02,7.67-2.78,13.4c-0.43,1.41,0.07,2.84,1.55,2.39c10.61-3.24,33.9-5.33,55.97-6.28"/>
		<path id="kvg:051fa-s3" kvg:type="㇑" d="M86.31,30.63c0.94,1.37,1.17,3,0.94,4.87c-0.62,5.12-0.86,7.07-1.66,13.48c-0.15,1.19-0.34,1.9-0.51,3.4"/>
	</g>
	<g id="kvg:051fa-g3" kvg:element="凵" kvg:radical="tradit">
		<path id="kvg:051fa-s4" kvg:type="㇄a" d="M25.27,71.13c1.11,1.11,1.6,2.74,1.31,4.29c-0.53,2.8-1.27,8.92-3.03,14.65c-0.43,1.41,0.57,3.11,2.05,2.64c12.9-4.08,41.9-6.21,59.47-7.03"/>
		<path id="kvg:051fa-s5" kvg:type="㇑" d="M85.06,66.88c1.06,1.49,1.56,3.12,1.44,5.37c-0.27,4.8-0.23,9.14-0.45,13.51c-0.08,1.54-0.17,3.17-0.3,4.99"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_051fa" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 42.25 11.63)">1</text>
	<text transform="matrix(1 0 0 1 20.25 35.63)">2</text>
	<text transform="matrix(1 0 0 1 76.75 29.13)">3</text>
	<text transform="matrix(1 0 0 1 16.75 71.13)">4</text>
	<text transform="matrix(1 0 0 1 75.75 67.50)">5</text>
</g>
</svg>
`, // 出
  'U+4E0A': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_04e0a" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:04e0a" kvg:element="上">
	<g id="kvg:04e0a-g1" kvg:element="卜" kvg:radical="nelson">
		<path id="kvg:04e0a-s1" kvg:type="㇑a" d="M52.31,15.88c1.15,1.15,2.01,3.12,2.01,5.12c0,0.82-0.22,63.62-0.25,64.63"/>
		<path id="kvg:04e0a-s2" kvg:type="㇐b/㇔" d="M58,44.75c7-0.62,14.25-2.5,17.75-3c1.38-0.2,3.5-0.38,4.75,0"/>
	</g>
	<g id="kvg:04e0a-g2" kvg:element="一" kvg:radical="tradit">
		<path id="kvg:04e0a-s3" kvg:type="㇐" d="M13.38,88.28c3.6,1.15,7.45,0.62,11.13,0.34c16.23-1.23,41.16-2.66,60.24-2.92c3.65-0.05,7.47-0.32,11,0.82"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_04e0a" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 43.50 16.28)">1</text>
	<text transform="matrix(1 0 0 1 60.25 41.50)">2</text>
	<text transform="matrix(1 0 0 1 5.50 88.50)">3</text>
</g>
</svg>
`, // 上
  'U+751F': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_0751f" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:0751f" kvg:element="生" kvg:radical="general">
	<path id="kvg:0751f-s1" kvg:type="㇒" d="M31.26,25.89c0.36,1.36,0.35,2.65-0.05,3.79c-2.34,6.69-7.24,17.22-14.96,24.19"/>
	<path id="kvg:0751f-s2" kvg:type="㇐" d="M31.13,40.67c2.37,0.33,4.03,0.07,5.64-0.12c9.5-1.1,25.15-4.12,35.35-5.83c2.51-0.42,4.86-0.73,7.38-0.33"/>
	<path id="kvg:0751f-s3" kvg:type="㇑a" d="M52.31,12.63c1.28,1.28,2.01,3.12,2.01,5.23c0,4.01,0,65.14,0,69.77"/>
	<path id="kvg:0751f-s4" kvg:type="㇐" d="M29.38,64.03c2.64,0.67,5.38,0.31,8.04-0.02C49.45,62.51,62.16,61,72.5,59.86c2.38-0.26,4.99-0.76,7.38-0.23"/>
	<path id="kvg:0751f-s5" kvg:type="㇐" d="M15.75,90.25c3.04,0.75,6.21,0.94,8.4,0.8C40.62,90,68.12,86.5,83.3,85.75c3.63-0.18,7.68,0,10.07,0.73"/>
</g>
</g>
<g id="kvg:StrokeNumbers_0751f" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 22.75 25.63)">1</text>
	<text transform="matrix(1 0 0 1 36.00 37.28)">2</text>
	<text transform="matrix(1 0 0 1 42.50 10.50)">3</text>
	<text transform="matrix(1 0 0 1 21.50 66.13)">4</text>
	<text transform="matrix(1 0 0 1 8.50 89.50)">5</text>
</g>
</svg>
`, // 生
  'U+6642': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_06642" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:06642" kvg:element="時">
	<g id="kvg:06642-g1" kvg:element="日" kvg:position="left" kvg:radical="general">
		<path id="kvg:06642-s1" kvg:type="㇑" d="M16,29.84c0.75,0.66,1.21,1.62,1.21,3.07c0,1.18-0.16,30.08-0.21,40.85c-0.01,2.42-0.02,3.95-0.02,4.08"/>
		<path id="kvg:06642-s2" kvg:type="㇕a" d="M17.78,30.74c4.65-0.63,16.12-2.07,17.6-2.25c1.52-0.18,3,1.5,2.88,2.57c-0.24,2.17-0.36,24.9-0.35,40.79c0,1.63-0.12,3.35-0.12,4.43"/>
		<path id="kvg:06642-s3" kvg:type="㇐a" d="M18.75,52c4.5-0.75,13.5-2.12,18.22-2.35"/>
		<path id="kvg:06642-s4" kvg:type="㇐a" d="M17.8,74.52c6.2-0.92,11.45-1.89,18.94-2.7"/>
	</g>
	<g id="kvg:06642-g2" kvg:element="寺" kvg:position="right" kvg:phon="寺">
		<g id="kvg:06642-g3" kvg:element="土">
			<path id="kvg:06642-s5" kvg:type="㇐" d="M51.44,29.03c1.37,0.44,3.63,0.34,5,0.19c9.79-1.09,16.34-2.34,25.62-3.08c2.27-0.18,3.9-0.04,5.04,0.18"/>
			<path id="kvg:06642-s6" kvg:type="㇑a" d="M67.59,11.37c0.89,0.9,1.59,2.24,1.59,3.75c0,8.39,0.03,27.02,0.03,27.6"/>
			<path id="kvg:06642-s7" kvg:type="㇐" d="M45.38,45.35c1.49,0.44,4.21,0.59,5.71,0.44c11.29-1.16,25.66-3.29,39.2-3.99c2.48-0.13,3.97,0.21,5.21,0.43"/>
		</g>
		<g id="kvg:06642-g4" kvg:element="寸">
			<path id="kvg:06642-s8" kvg:type="㇐" d="M46,60.99c1.43,0.46,4.04,0.58,5.49,0.46c12.01-1.07,26.89-3.07,39.07-3.89c2.38-0.16,4.41,0.22,5.6,0.44"/>
			<path id="kvg:06642-s9" kvg:type="㇚" d="M78.07,46.08c1.11,1.11,1.66,2.56,1.71,5.06c0.23,12.03-0.09,34.43-0.09,38.52c0,9.83-5.42,2.19-7.66-0.04"/>
			<path id="kvg:06642-s10" kvg:type="㇔" d="M56.75,70.38c2.87,1.76,6.55,6.38,7.27,9.12"/>
		</g>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_06642" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 9.75 39.13)">1</text>
	<text transform="matrix(1 0 0 1 18.50 27.50)">2</text>
	<text transform="matrix(1 0 0 1 21.50 48.13)">3</text>
	<text transform="matrix(1 0 0 1 21.33 70.50)">4</text>
	<text transform="matrix(1 0 0 1 45.50 27.13)">5</text>
	<text transform="matrix(1 0 0 1 58.50 11.50)">6</text>
	<text transform="matrix(1 0 0 1 45.75 42.13)">7</text>
	<text transform="matrix(1 0 0 1 44.25 57.13)">8</text>
	<text transform="matrix(1 0 0 1 71.25 54.13)">9</text>
	<text transform="matrix(1 0 0 1 47.25 76.63)">10</text>
</g>
</svg>
`, // 時
  'U+624B': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_0624b" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:0624b" kvg:element="手" kvg:radical="general">
	<path id="kvg:0624b-s1" kvg:type="㇒" d="M61.48,11.5c0.02,1-0.61,1.88-1.67,2.9c-3.27,3.15-13.69,8.23-28.57,11.85"/>
	<path id="kvg:0624b-s2" kvg:type="㇐" d="M26.38,42.92c1.8,0.46,3.61,0.67,5.68,0.38C46,41.38,58.4,39,71.37,37.75c1.92-0.19,4.62-0.38,7.25,0.04"/>
	<path id="kvg:0624b-s3" kvg:type="㇐" d="M13.27,62.87c2.71,0.63,4.86,0.6,7.22,0.38c22.63-2.12,46.13-5.62,67.7-7c2.01-0.13,4.83,0,7.46,0.37"/>
	<path id="kvg:0624b-s4" kvg:type="㇁" d="M48.88,23.55C60.38,31,62.73,63.66,57.83,89.87c-2.08,11.13-8.64,2.34-9.89,1.17"/>
</g>
</g>
<g id="kvg:StrokeNumbers_0624b" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 53.50 11.50)">1</text>
	<text transform="matrix(1 0 0 1 17.50 45.50)">2</text>
	<text transform="matrix(1 0 0 1 5.50 66.50)">3</text>
	<text transform="matrix(1 0 0 1 44.50 32.50)">4</text>
</g>
</svg>
`, // 手
  'U+884C': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_0884c" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:0884c" kvg:element="行" kvg:radical="general">
	<g id="kvg:0884c-g1" kvg:element="彳" kvg:position="left">
		<path id="kvg:0884c-s1" kvg:type="㇒" d="M32.49,12c-0.12,1-0.45,1.9-1.1,2.62C28.29,18.06,22.2,22.6,12.5,28"/>
		<g id="kvg:0884c-g2" kvg:element="亻" kvg:variant="true" kvg:original="人">
			<path id="kvg:0884c-s2" kvg:type="㇒" d="M36.5,31.75c0.07,0.73,0.08,2.28-0.39,3.18C32.12,42.5,23.83,52.5,11,62.75"/>
			<path id="kvg:0884c-s3" kvg:type="㇑" d="M25.57,51.75c0.9,0.9,1.23,2.25,1.23,3.26c0,0.72,0.04,24.47-0.07,35.49c-0.02,2.19-0.04,3.87-0.07,4.75"/>
		</g>
	</g>
	<g id="kvg:0884c-g3" kvg:position="right">
		<path id="kvg:0884c-s4" kvg:type="㇐" d="M50.5,18.45c1.44,0.35,3.81,0.52,5.23,0.35c7.14-0.8,16.01-2.43,24.49-3.06c2.38-0.18,3.83-0.06,5.02,0.11"/>
		<path id="kvg:0884c-s5" kvg:type="㇐" d="M43.13,41.42c1.5,0.38,4.27,0.58,5.76,0.38c12.86-1.67,28.86-4.05,41.85-5.38c2.49-0.26,4.01,0.18,5.26,0.37"/>
		<path id="kvg:0884c-s6" kvg:type="㇚" d="M71.52,41.33c1.26,1.26,1.76,2.79,1.76,5.27c0,14.56-0.26,38.66-0.26,43.62c0,8.03-7.21-0.5-8.71-1.75"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_0884c" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 25.75 10.50)">1</text>
	<text transform="matrix(1 0 0 1 28.50 31.50)">2</text>
	<text transform="matrix(1 0 0 1 19.50 65.50)">3</text>
	<text transform="matrix(1 0 0 1 49.50 15.50)">4</text>
	<text transform="matrix(1 0 0 1 43.50 38.50)">5</text>
	<text transform="matrix(1 0 0 1 64.50 50.50)">6</text>
</g>
</svg>
`, // 行
  'U+524D': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_0524d" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:0524d" kvg:element="前">
	<g id="kvg:0524d-g1" kvg:position="top" kvg:phon="歬1V">
		<g id="kvg:0524d-g2" kvg:element="八" kvg:variant="true" kvg:radical="nelson">
			<path id="kvg:0524d-s1" kvg:type="㇔" d="M33.5,14.5c3.34,2.07,8.64,8.5,9.48,11.72"/>
			<path id="kvg:0524d-s2" kvg:type="㇒" d="M72.67,12c0.26,1.14,0.07,2.23-0.52,3.19c-2.12,3.41-6.02,8.65-8.6,11.31"/>
		</g>
		<path id="kvg:0524d-s3" kvg:type="㇐" d="M13.38,33.24c2.63,0.72,7.46,0.94,10.08,0.72c21.67-1.83,39.8-3.58,62.68-4.61c4.37-0.2,7.01,0.34,9.2,0.7"/>
	</g>
	<g id="kvg:0524d-g3" kvg:position="bottom">
		<g id="kvg:0524d-g4" kvg:element="月" kvg:variant="true" kvg:phon="歬2V">
			<path id="kvg:0524d-s4" kvg:type="㇑" d="M24.65,45.46c1.1,1.29,1.63,2.92,1.63,4.17c0,3.05,0.1,28.65,0.08,40.62c0,3.23-0.03,5.46-0.1,6"/>
			<path id="kvg:0524d-s5" kvg:type="㇆a" d="M27.01,46.8c2.3-0.41,13.37-2.3,17.2-2.9c2.2-0.34,3.51,1.1,3.51,3.24c0,1.02-0.16,30.82-0.16,44.63c0,5.48-3.79,2.98-5.93,0.53"/>
			<path id="kvg:0524d-s6" kvg:type="㇐a" d="M27.65,60.01c5.72-0.76,13.63-1.81,18.59-2.32"/>
			<path id="kvg:0524d-s7" kvg:type="㇐a" d="M27.57,73.47c4.41-0.51,13.3-1.54,18.4-1.89"/>
		</g>
		<g id="kvg:0524d-g5" kvg:element="刂" kvg:variant="true" kvg:original="刀" kvg:radical="tradit">
			<path id="kvg:0524d-s8" kvg:type="㇑" d="M62.27,47.58c1.2,1.2,1.76,2.67,1.76,4.58c0,8.93-0.01,15.1-0.09,18.59c-0.04,1.49-0.09,2.76-0.16,4.05"/>
			<path id="kvg:0524d-s9" kvg:type="㇚" d="M78.85,39.25c1.26,1.26,2.01,2.88,2.01,5.02c0,14.56-0.01,42.91-0.01,47.87c0,8.62-5.96,1-7.46-0.25"/>
		</g>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_0524d" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 26.25 13.50)">1</text>
	<text transform="matrix(1 0 0 1 63.50 10.50)">2</text>
	<text transform="matrix(1 0 0 1 6.50 34.50)">3</text>
	<text transform="matrix(1 0 0 1 18.50 52.63)">4</text>
	<text transform="matrix(1 0 0 1 27.50 44.50)">5</text>
	<text transform="matrix(1 0 0 1 29.50 57.13)">6</text>
	<text transform="matrix(1 0 0 1 29.50 72.50)">7</text>
	<text transform="matrix(1 0 0 1 56.25 45.50)">8</text>
	<text transform="matrix(1 0 0 1 70.50 42.50)">9</text>
</g>
</svg>
`, // 前
  'U+5F8C': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_05f8c" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:05f8c" kvg:element="後">
	<g id="kvg:05f8c-g1" kvg:element="彳" kvg:position="left" kvg:radical="general">
		<path id="kvg:05f8c-s1" kvg:type="㇒" d="M34.25,18.38c0,1.3-0.24,2.26-0.93,3.05c-3.57,4.07-8.94,8.7-15.91,13.39"/>
		<g id="kvg:05f8c-g2" kvg:element="亻" kvg:variant="true" kvg:original="人">
			<path id="kvg:05f8c-s2" kvg:type="㇒" d="M38.75,36.62c0.14,1.32-0.42,2.67-1.13,3.79c-3.45,5.4-11.43,14.17-22.37,22.71"/>
			<path id="kvg:05f8c-s3" kvg:type="㇑" d="M28.4,54.36c0.81,0.81,1.38,2.02,1.38,3.28c0,0.68,0.03,25.57-0.07,35.86c-0.02,1.74-0.04,3.05-0.05,3.75"/>
		</g>
	</g>
	<g id="kvg:05f8c-g3" kvg:position="right">
		<g id="kvg:05f8c-g4" kvg:element="幺">
			<path id="kvg:05f8c-s4" kvg:type="㇜" d="M61.16,12.62c0.29,1.07,0.21,2.43-0.39,3.54c-2.52,4.6-6.1,9.01-9.88,12.93c-1.01,1.05-1.26,2.17,0,2.68c2.96,1.19,6.3,3.11,8.88,5.07"/>
			<path id="kvg:05f8c-s5" kvg:type="㇜" d="M76.35,20.12c0.27,1.25-0.3,2.56-1,3.31c-7.6,8.19-16.6,16.57-26.61,25.32c-1.25,1.1-0.74,1.76,0.74,1.41C55.72,48.69,74.5,44.4,82.5,43"/>
			<path id="kvg:05f8c-s6" kvg:type="㇔" d="M77.88,36.25c3.66,2.21,9.46,9.07,10.38,12.5"/>
		</g>
		<g id="kvg:05f8c-g5" kvg:element="夂">
			<path id="kvg:05f8c-s7" kvg:type="㇒" d="M57.75,53c0.09,1.13,0.02,2.27-0.4,3.33c-2.2,5.51-7.08,13.22-15.6,20.92"/>
			<path id="kvg:05f8c-s8" kvg:type="㇇" d="M59.31,59.82c1.17,0.13,2.31,0.02,3.29-0.09c2.65-0.29,9.84-1.39,13.62-2.29c2.59-0.62,3.24,0.68,2.67,2.4C75.25,70.75,59.25,88.88,43.02,96.5"/>
			<path id="kvg:05f8c-s9" kvg:type="㇏" d="M54.75,67.5c2.52,0,19.5,15.75,31.17,24.23c2.31,1.68,4.74,3.38,7.58,4.01"/>
		</g>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_05f8c" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 26.50 18.50)">1</text>
	<text transform="matrix(1 0 0 1 30.50 39.50)">2</text>
	<text transform="matrix(1 0 0 1 23.25 66.50)">3</text>
	<text transform="matrix(1 0 0 1 52.50 14.50)">4</text>
	<text transform="matrix(1 0 0 1 68.50 21.50)">5</text>
	<text transform="matrix(1 0 0 1 78.50 34.63)">6</text>
	<text transform="matrix(1 0 0 1 49.50 60.50)">7</text>
	<text transform="matrix(1 0 0 1 63.50 56.50)">8</text>
	<text transform="matrix(1 0 0 1 53.25 76.63)">9</text>
</g>
</svg>
`, // 後
  'U+898B': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_0898b" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:0898b" kvg:element="見" kvg:radical="general">
	<g id="kvg:0898b-g1" kvg:element="目" kvg:position="top">
		<path id="kvg:0898b-s1" kvg:type="㇑" d="M32.5,15.46c0.96,0.96,1.18,2.1,1.18,3.52c0,1.12,0.07,27.43-0.02,39.27c-0.02,3.12-0.02,5.21,0.02,5.5"/>
		<path id="kvg:0898b-s2" kvg:type="㇕a" d="M34.65,17.15c9.23-1.27,22.23-2.65,31.1-3.65c2.99-0.34,4.26,1.01,4.26,3.55c0,2.5-0.1,28.08-0.14,38.96c-0.01,2.91-0.02,4.75-0.02,4.79"/>
		<path id="kvg:0898b-s3" kvg:type="㇐a" d="M34.84,31.1c7.28-0.6,25.03-2.98,33.9-3.38"/>
		<path id="kvg:0898b-s4" kvg:type="㇐a" d="M34.86,44.63C43.38,44,59,42.12,68.6,41.51"/>
		<path id="kvg:0898b-s5" kvg:type="㇐a" d="M34.71,59.66C44.5,59,58.38,57.5,68.45,57.03"/>
	</g>
	<g id="kvg:0898b-g2" kvg:element="儿" kvg:position="bottom">
		<path id="kvg:0898b-s6" kvg:type="㇒" d="M41.99,66.75c0.26,1.5,0.01,2.99-0.41,4.04c-2.7,6.83-13.83,20.83-28.41,27.87"/>
		<path id="kvg:0898b-s7" kvg:type="㇟" d="M54.49,61.37c1.07,1.07,1.33,2.59,1.38,4.43c0.2,8.19,0.04,6.2,0.04,18.2c0,10.12,1.23,11.53,18.54,11.53c18.81,0,19.81-1.53,19.81-10.12"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_0898b" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 26.50 23.50)">1</text>
	<text transform="matrix(1 0 0 1 35.50 13.50)">2</text>
	<text transform="matrix(1 0 0 1 38.25 27.43)">3</text>
	<text transform="matrix(1 0 0 1 38.25 40.63)">4</text>
	<text transform="matrix(1 0 0 1 38.25 55.63)">5</text>
	<text transform="matrix(1 0 0 1 32.50 74.50)">6</text>
	<text transform="matrix(1 0 0 1 48.50 69.50)">7</text>
</g>
</svg>
`, // 見
  'U+4E0B': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_04e0b" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:04e0b" kvg:element="下">
	<g id="kvg:04e0b-g1" kvg:element="一" kvg:radical="general">
		<path id="kvg:04e0b-s1" kvg:type="㇐" d="M13.25,22.5c0.94,0.23,5.18,0.96,7.74,0.75c17.87-1.5,46.54-4.75,66.38-4.75c2.92,0,6.42,0.75,7.88,1.25"/>
	</g>
	<g id="kvg:04e0b-g2" kvg:element="卜" kvg:variant="true">
		<path id="kvg:04e0b-s2" kvg:type="㇑" d="M52.97,23.25c0.93,1.07,1.56,2.75,1.56,5.3c0,8.65-0.2,39.42-0.27,57.2c-0.02,3.86-0.02,5.89-0.02,8.25"/>
		<path id="kvg:04e0b-s3" kvg:type="㇔" d="M67.83,37.17C72.75,39.5,79.88,47.62,82,52.12"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_04e0b" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 6.50 22.63)">1</text>
	<text transform="matrix(1 0 0 1 46.75 33.13)">2</text>
	<text transform="matrix(1 0 0 1 62.50 32.13)">3</text>
</g>
</svg>
`, // 下
  'U+6708': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_06708" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:06708" kvg:element="月" kvg:radical="general">
	<path id="kvg:06708-s1" kvg:type="㇓" d="M34.25,16.25c1,1,1.48,2.38,1.5,4c0.38,33.62,2.38,59.38-11,73.25"/>
	<path id="kvg:06708-s2" kvg:type="㇆a" d="M36.25,19c4.12-0.62,31.49-4.78,33.25-5c4-0.5,5.5,1.12,5.5,4.75c0,2.76-0.5,49.25-0.5,69.5c0,13-6.25,4-8.75,1.75"/>
	<path id="kvg:06708-s3" kvg:type="㇐a" d="M37.25,38c10.25-1.5,27.25-3.75,36.25-4.5"/>
	<path id="kvg:06708-s4" kvg:type="㇐a" d="M37,58.25c8.75-1.12,27-3.5,36.25-4"/>
</g>
</g>
<g id="kvg:StrokeNumbers_06708" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 27.50 23.43)">1</text>
	<text transform="matrix(1 0 0 1 37.50 15.50)">2</text>
	<text transform="matrix(1 0 0 1 40.00 33.50)">3</text>
	<text transform="matrix(1 0 0 1 40.00 54.50)">4</text>
</g>
</svg>
`, // 月
  'U+5B50': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_05b50" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:05b50" kvg:element="子" kvg:radical="general">
	<path id="kvg:05b50-s1" kvg:type="㇖" d="M33.28,19.04c1.84,0.71,3.7,0.86,5.4,0.63c4.95-0.67,27.95-4.58,29.86-4.92c3.46-0.62,4.06,1.36,2.11,3.58c-1.95,2.22-11.41,13.17-16.35,17.19"/>
	<path id="kvg:05b50-s2" kvg:type="㇁" d="M52.48,37.74c6.42,2.97,11.75,30.73,5.24,52.57c-2.8,9.38-8.09,2.96-10.47,0.99"/>
	<path id="kvg:05b50-s3" kvg:type="㇐" d="M12.25,51.48c3.75,1.14,8.79,1.03,12.48,0.49c16.77-2.47,42.86-5.84,58.53-6.75c4.26-0.25,9.11-0.34,13.11,0.57"/>
</g>
</g>
<g id="kvg:StrokeNumbers_05b50" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 25.50 20.50)">1</text>
	<text transform="matrix(1 0 0 1 44.50 42.50)">2</text>
	<text transform="matrix(1 0 0 1 4.50 53.50)">3</text>
</g>
</svg>
`, // 子
  'U+5206': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_05206" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:05206" kvg:element="分">
	<g id="kvg:05206-g1" kvg:element="八" kvg:position="top" kvg:radical="nelson">
		<path id="kvg:05206-s1" kvg:type="㇒" d="M41.12,19.38c0.25,1.24-0.44,3.01-1.1,4.08C34.31,32.72,27.13,40.62,13,51.25"/>
		<path id="kvg:05206-s2" kvg:type="㇏" d="M54.69,13.75c7.56-0.12,20.68,19.17,29.41,25.95c3.07,2.39,6.02,4.05,10.4,5.3"/>
	</g>
	<g id="kvg:05206-g2" kvg:element="刀" kvg:position="bottom" kvg:radical="tradit">
		<path id="kvg:05206-s3" kvg:type="㇆" d="M29.35,55.37c2.42,0.83,4.97,0.75,7.42,0.37c11.06-1.7,28.87-5.3,34.1-5.76c3.69-0.33,5.08,1.48,4.88,3.77c-0.54,6.05-5.94,29.03-10.5,36.3c-4.99,7.96-5.74,4.21-9.84-0.49"/>
		<path id="kvg:05206-s4" kvg:type="㇒" d="M49.12,57.25c0.15,1.49,0.06,2.72-0.56,4.08C43.5,72.5,35.75,82,22.5,90.75"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_05206" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 32.50 19.50)">1</text>
	<text transform="matrix(1 0 0 1 50.50 11.50)">2</text>
	<text transform="matrix(1 0 0 1 30.50 52.50)">3</text>
	<text transform="matrix(1 0 0 1 39.50 65.50)">4</text>
</g>
</svg>
`, // 分
  'U+9593': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_09593" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:09593" kvg:element="間">
	<g id="kvg:09593-g1" kvg:element="門" kvg:position="kamae" kvg:radical="general">
		<g id="kvg:09593-g2" kvg:position="left">
			<path id="kvg:09593-s1" kvg:type="㇑" d="M18.64,15.3c0.71,0.71,1.18,1.82,1.18,3.43c0,3.89-0.05,56.65-0.19,72.77c-0.02,1.92-0.03,4.03-0.05,4.65"/>
			<path id="kvg:09593-s2" kvg:type="㇕a" d="M21.01,16.81c5.75-0.6,18.73-2.74,20.5-2.84c1.85-0.1,2.86,0.28,2.9,2.02c0.06,2.75-0.5,16.1-0.85,20.76c-0.12,1.55-0.19,2.57-0.19,2.7"/>
			<path id="kvg:09593-s3" kvg:type="㇐a" d="M20.95,27.27c5.99-0.61,14.92-2.02,21.88-2.6"/>
			<path id="kvg:09593-s4" kvg:type="㇐a" d="M21.02,39.04c8.11-1.19,14.14-2.1,21.31-2.64"/>
		</g>
		<g id="kvg:09593-g3" kvg:position="right">
			<path id="kvg:09593-s5" kvg:type="㇑" d="M63.19,13.1c0.98,0.98,1.34,2.15,1.34,2.97c0,5.8-0.08,12.65-0.06,18.93c0.01,2.01,0.02,3.4,0.06,3.58"/>
			<path id="kvg:09593-s6" kvg:type="㇆a" d="M65.32,14.77c5.97-0.68,20.69-3.19,22.38-3.28c1.8-0.09,2.81,0.88,2.81,2.82c0,17-0.22,66.12-0.22,78.44c0,10.5-6.35,1.36-7.72,0.23"/>
			<path id="kvg:09593-s7" kvg:type="㇐a" d="M65.63,24.79c4.49-0.42,19.73-1.99,23.35-1.99"/>
			<path id="kvg:09593-s8" kvg:type="㇐a" d="M65.22,36.07c6.41-0.32,16.53-1.32,23.49-1.81"/>
		</g>
	</g>
	<g id="kvg:09593-g4" kvg:element="日">
		<path id="kvg:09593-s9" kvg:type="㇑" d="M40.56,50.95c0.74,0.74,1.04,1.93,1.04,2.99c0,0.83-0.08,20.84-0.05,29.06c0.01,2.25,0.02,2.77,0.05,3"/>
		<path id="kvg:09593-s10" kvg:type="㇕a" d="M42.26,52.09c5.56-0.48,19.71-1.98,21.3-2.1c1.68-0.13,2.76,1.46,2.63,2.24c-0.21,1.24-0.41,20.66-0.48,29.02c-0.02,2.29-0.03,3.8-0.03,3.97"/>
		<path id="kvg:09593-s11" kvg:type="㇐a" d="M42.64,66.6c5.11-0.48,17.36-1.73,21.88-2.07"/>
		<path id="kvg:09593-s12" kvg:type="㇐a" d="M42.25,82.8c5.13-0.3,17-1.55,22.26-2.05"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_09593" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 12.75 23.50)">1</text>
	<text transform="matrix(1 0 0 1 21.75 13.63)">2</text>
	<text transform="matrix(1 0 0 1 24.75 24.50)">3</text>
	<text transform="matrix(1 0 0 1 24.75 35.50)">4</text>
	<text transform="matrix(1 0 0 1 56.50 21.50)">5</text>
	<text transform="matrix(1 0 0 1 65.25 11.50)">6</text>
	<text transform="matrix(1 0 0 1 68.54 22.50)">7</text>
	<text transform="matrix(1 0 0 1 68.50 33.50)">8</text>
	<text transform="matrix(1 0 0 1 34.50 57.50)">9</text>
	<text transform="matrix(1 0 0 1 42.75 48.50)">10</text>
	<text transform="matrix(1 0 0 1 44.50 63.50)">11</text>
	<text transform="matrix(1 0 0 1 44.31 79.50)">12</text>
</g>
</svg>
`, // 間
  'U+5B66': `<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2009/2010/2011 Ulrich Apel.
This work is distributed under the conditions of the Creative Commons
Attribution-Share Alike 3.0 Licence. This means you are free:
* to Share - to copy, distribute and transmit the work
* to Remix - to adapt the work

Under the following conditions:
* Attribution. You must attribute the work by stating your use of KanjiVG in
  your own copyright header and linking to KanjiVG's website
  (http://kanjivg.tagaini.net)
* Share Alike. If you alter, transform, or build upon this work, you may
  distribute the resulting work only under the same or similar license to this
  one.

See http://creativecommons.org/licenses/by-sa/3.0/ for more details.
-->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
<!ATTLIST g
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:element CDATA #IMPLIED
kvg:variant CDATA #IMPLIED
kvg:partial CDATA #IMPLIED
kvg:original CDATA #IMPLIED
kvg:part CDATA #IMPLIED
kvg:number CDATA #IMPLIED
kvg:tradForm CDATA #IMPLIED
kvg:radicalForm CDATA #IMPLIED
kvg:position CDATA #IMPLIED
kvg:radical CDATA #IMPLIED
kvg:phon CDATA #IMPLIED >
<!ATTLIST path
xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
kvg:type CDATA #IMPLIED >
]>
<svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">
<g id="kvg:StrokePaths_05b66" style="fill:none;stroke:#000000;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;">
<g id="kvg:05b66" kvg:element="学">
	<g id="kvg:05b66-g1" kvg:position="top" kvg:phon="𦥯">
		<g id="kvg:05b66-g2" kvg:element="⺍" kvg:original="つ">
			<path id="kvg:05b66-s1" kvg:type="㇔" d="M29.5,17.25c3.5,3,6.5,7.25,7.75,9.75"/>
			<path id="kvg:05b66-s2" kvg:type="㇔" d="M49,12c1.25,2,4.75,8.25,5.25,11.5"/>
			<path id="kvg:05b66-s3" kvg:type="㇒" d="M75,11c0.25,1.75-0.12,2.75-0.75,4.25c-1.29,3.1-4.25,7.38-6.5,9.75"/>
		</g>
		<g id="kvg:05b66-g3" kvg:element="冖">
			<path id="kvg:05b66-s4" kvg:type="㇔" d="M21.25,33.75c-0.12,4.75-2,12.5-3.75,16.25"/>
			<path id="kvg:05b66-s5" kvg:type="㇖b" d="M23.5,36.5c17-1.62,42.38-5.5,60-5.75c9.5-0.13,4.12,5.12,0,9"/>
		</g>
	</g>
	<g id="kvg:05b66-g4" kvg:element="子" kvg:position="bottom" kvg:radical="general">
		<path id="kvg:05b66-s6" kvg:type="㇖" d="M37.25,46.5c1,0.25,3.75,0.25,5.5-0.25s18.25-4,20-4s2.75,0.75,1,2.25S54.5,53.5,53,54.75"/>
		<path id="kvg:05b66-s7" kvg:type="㇁" d="M50.75,55.75c4,8.75,7.18,24.67,1.75,38c-2.75,6.75-7.75,1.25-9.75-2"/>
		<path id="kvg:05b66-s8" kvg:type="㇐" d="M15.75,67.75c1.75,1,4.64,1.36,7.5,1c15.88-2,44.43-6.25,61.37-5.5c2.5,0.11,4.72,0.25,6.39,1"/>
	</g>
</g>
</g>
<g id="kvg:StrokeNumbers_05b66" style="font-size:8;fill:#808080">
	<text transform="matrix(1 0 0 1 20.25 13.63)">1</text>
	<text transform="matrix(1 0 0 1 39.75 8.50)">2</text>
	<text transform="matrix(1 0 0 1 66.50 8.50)">3</text>
	<text transform="matrix(1 0 0 1 14.50 34.63)">4</text>
	<text transform="matrix(1 0 0 1 24.50 32.50)">5</text>
	<text transform="matrix(1 0 0 1 29.25 48.50)">6</text>
	<text transform="matrix(1 0 0 1 44.50 58.63)">7</text>
	<text transform="matrix(1 0 0 1 8.50 72.50)">8</text>
</g>
</svg>
`, // 学
};

/**
 * Get bundled SVG content for a kanji
 * @param kanjiId - Unicode ID (e.g., "U+4E00")
 * @returns SVG content string, or null if not bundled
 */
export function getBundledSVG(kanjiId: string): string | null {
  return BUNDLED_SVG_DATA[kanjiId] || null;
}

/**
 * Check if kanji is bundled
 * @param kanjiId - Unicode ID
 * @returns true if bundled
 */
export function isBundled(kanjiId: string): boolean {
  return BUNDLED_KANJI_IDS.includes(kanjiId);
}
