/**
 * KanjiVG Bundled Kanji Index
 *
 * Data Attribution:
 * KanjiVG data © Ulrich Apel, CC BY-SA 3.0
 * https://kanjivg.tagaini.net/
 *
 * NOTE: This is a minimal bundle for testing. Production bundle
 * should contain 500 JLPT kanji generated by scripts/download-kanjivg-bundle.js
 */

// Sample bundled kanji (for testing - matches our test fixtures)
export const BUNDLED_KANJI_IDS = [
  'U+4E00', // 一
  'U+4EBA', // 人
  'U+56FD', // 国
  'U+6642', // 時
];

/**
 * Get bundled SVG content for a kanji
 *
 * NOTE: In production, this would dynamically require SVG files.
 * For now, returns null as bundle loading is handled by integration service.
 *
 * @param kanjiId - Unicode ID (e.g., "U+4E00")
 * @returns SVG content string, or null if not bundled
 */
export function getBundledSVG(kanjiId: string): string | null {
  // Placeholder - bundle loading handled by KanjiVGIntegrationService
  // using test fixtures for now
  return null;
}

/**
 * Check if kanji is bundled
 * @param kanjiId - Unicode ID
 * @returns true if bundled
 */
export function isBundled(kanjiId: string): boolean {
  return BUNDLED_KANJI_IDS.includes(kanjiId);
}
